---
language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

# install:
#   - pip install -r requirements.txt

script:
  - python -m pytest tests

before_install:
  - pip install -r requirements.txt
  - python setup.py install
