---
language: python

python:
  - "2.7"
  - "3.3"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - py.test tests

before_install:
  - pip install sphinx>=1.6.3
  - pip install pytest
  - pip install mock
  - python setup.py install
