# container for editing and generating agavepy
#
#

slt-agavepy:
  image: dsagavepy
  container_name: slt-agavepy
  command: python setup.py install

  volumes:
    - './agavepy/resources:/agavepy/agavepy/resources'
