"""Provides constants for the AgavePy package
"""
__all__ = ['PLATFORM', 'BASE_URL', 'SESSION_CACHE_DIRS',
           'CLIENT_FILENAME', 'CONFIGS_FILENAME', 'AGPY_FILENAME',
           'CACHES_DIR_NAME', 'ENV_USERNAME', 'ENV_PASSWORD',
           'ENV_TOKEN', 'ENV_REFRESH_TOKEN']

PLATFORM = 'Tapis'
BASE_URL = 'https://api.tacc.utexas.edu'

SESSION_CACHE_DIRS = ('TAPIS_CACHE_DIR', 'TAPIS_CACHE', 'AGAVE_CACHE_DIR')

AGPY_FILENAME = '.agpy'
CACHES_DIR_NAME = '.agave'
CLIENT_FILENAME = 'current'
CONFIGS_FILENAME = 'config.json'

ENV_USERNAME = 'TAPIS_USERNAME'
ENV_PASSWORD = 'TAPIS_PASSWORD'
ENV_TOKEN = 'TAPIS_TOKEN'
ENV_REFRESH_TOKEN = 'TAPIS_REFRESH_TOKEN'
