# Simple docker image for running the agavepy test suite.
# Image: jstubbs/agavepy_testrunner
# To use this image, mount test_credentials.json to /agavepy/agavepy/tests/test_credentials.json and
# mount a large file to use for testing to /agavepy/agavepy/tests/test_largefile_upload_python_sdk

from python:2

RUN virtualenv ag

RUN git clone https://github.com/TACC/agavepy.git /agavepy

ADD cmd.sh /cmd.sh
RUN chmod +x /cmd.sh

CMD ["./cmd.sh"]
