# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = python -msphinx
SPHINXPROJ    = AgavePy
SOURCEDIR     = .
BUILDDIR      = _build

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

definitions: definitions-clean
	mkdir -p _static/definitions/ && \
	cp ../definitions/* _static/definitions/

definitions-clean:
	rm -rf _static/definitions/*

schemas: schemas-clean
	mkdir -p _static/schemas/ && \
	cp ../schemas/* _static/schemas/

schemas-clean:
	rm -rf _static/schemas/*

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)